config/routes.rb
Rails.application.routes.draw do
  resources :faculties
  get 'studentinfo/index'
  get 'placements/index'
  get 'faculties/index'
  get 'department/index'
  get 'aboutus/index'
  get 'home/index'
  get 'home/show'
  get 'home/new'
  get 'home/edit'
  get 'home/delete'
  #get'studentinfos/index'
  resources:home do
  	collection{post :import}
  end
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/faculty.rb
class Faculty < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/department_controller.rb
class DepartmentController < ApplicationController
  def index
  end
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @s=Student.all
  end

  def show
  end

  def new
    @s=Student.new
  end
  def create
    @s=Student.new(student_params)
    if @s.save
      redirect_to(action:'index')
    else
      render('new')
    end
  end

  def edit
  end
  def import
    Student.find(params[:file])
    redirect_to(action:'index')
  end

  def delete
  end
  private
  def student_params
    params.require(:Student).permit(:rollno,:name,:grade,:branch)
  end
end

app/controllers/placements_controller.rb
class PlacementsController < ApplicationController
  def index
  end
end

app/controllers/studentinfo_controller.rb
class StudentinfoController < ApplicationController
  def index
  end
end

app/controllers/studentinfos_controller.rb
class StudentinfosController < ApplicationController
  before_action :set_studentinfo, only: [:show, :edit, :update, :destroy]

  # GET /studentinfos
  # GET /studentinfos.json
  def index
    @studentinfos = Studentinfo.all
  end

  # GET /studentinfos/1
  # GET /studentinfos/1.json
  def show
  end

  # GET /studentinfos/new
  def new
    @studentinfo = Studentinfo.new
  end

  # GET /studentinfos/1/edit
  def edit
  end

  # POST /studentinfos
  # POST /studentinfos.json
  def create
    @studentinfo = Studentinfo.new(studentinfo_params)

    respond_to do |format|
      if @studentinfo.save
        format.html { redirect_to @studentinfo, notice: 'Studentinfo was successfully created.' }
        format.json { render :show, status: :created, location: @studentinfo }
      else
        format.html { render :new }
        format.json { render json: @studentinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studentinfos/1
  # PATCH/PUT /studentinfos/1.json
  def update
    respond_to do |format|
      if @studentinfo.update(studentinfo_params)
        format.html { redirect_to @studentinfo, notice: 'Studentinfo was successfully updated.' }
        format.json { render :show, status: :ok, location: @studentinfo }
      else
        format.html { render :edit }
        format.json { render json: @studentinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studentinfos/1
  # DELETE /studentinfos/1.json
  def destroy
    @studentinfo.destroy
    respond_to do |format|
      format.html { redirect_to studentinfos_url, notice: 'Studentinfo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_studentinfo
      @studentinfo = Studentinfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def studentinfo_params
      params.fetch(:studentinfo, {})
    end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/placements_helper.rb
module PlacementsHelper
end

app/helpers/studentinfo_helper.rb
module StudentinfoHelper
end

app/helpers/studentinfos_helper.rb
module StudentinfosHelper
end

app/views/aboutus/index.html.erb
<h1>Aboutus#index</h1>
<p>Find me in app/views/aboutus/index.html.erb</p>

app/views/department/index.html.erb
<h1>Department#index</h1>
<p>Find me in app/views/department/index.html.erb</p>

app/views/faculties/_form.html.erb
<%= form_with(model: faculty, local: true) do |form| %>
<% if faculty.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(faculty.errors.count,"error") %> prohibited this faculty from being saved:</h2>

<ul>
<% faculty.errors.full_messages.each do |message| %>
	<li><%= message %></li>li>
	<% end %>
	</ul>
	</div>
	<% end %>

	<div class="field">
	<%= form.label :name %>
	<%= form.text_field :name %>
	</div>

	<div class="field">
	<%= form.label :more %>
	<%= form.text_field :more %>
	</div>

<div class="field">
	<%= form.label :image %>
	<%= form.file_field :image %>
	</div>
<div class="actions">
<%= form.submit %>
</div>
<% end %>

app/views/faculties/edit.html.erb
<h1>Editing Faculty</h1>

<%= rnder 'form', faculty: @faculty %>

<%= link_to 'Show', @faculty %>
<%= link_to 'Back',faculties_path %>

app/views/faculties/index.html.erb
<h1>Faculties#index</h1>
<p>Find me in app/views/faculties/index.html.erb</p>

app/views/faculties/new.html.erb
<h1>New Faculty</h1>

<%= render 'form', faculty: @faculty %>

<%= link_to 'Back', faculties_path %>

app/views/faculties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<strong>Name:</strong>
<%= @faculty.name %>
</p>
<strong>Name:</strong>
<%= @faculty.more %>
</p>
<%= link_to 'Edit',edit_faculty_path@faculty) %>
<%= link_to 'Back', faculties_path %>

app/views/home/delete.html.erb
<h1>Home#delete</h1>
<p>Find me in app/views/home/delete.html.erb</p>

app/views/home/edit.html.erb
<h1>Home#edit</h1>
<p>Find me in app/views/home/edit.html.erb</p>

app/views/home/index.html.erb
<%=form_tag home_index_path,multipart:true do%>
<%=file_field_tag :file%>
<%=submit_tag ("importcsv")%>
<%end%>
<table>
<th>rollno</th>
<th>name</th>
<th>grade</th>
<th>branch</th>
<tr>
<%@s.each do |s|%>
<td><%=s.rollno%></td>
<td><%=s.name%></td>
<td><%=s.grade%></td>
<td><%=s.branch%></td>
</tr>
<%end%>
</table>

app/views/home/new.html.erb
<%=form_for(:Student,:url=>{:action=>'create'}) do |f|%>

<div class="form_fields"%>
<%=f.label :rollno,:class=>"control_label"%>
<%=f.text_field(:rollno)%>
</div>
<div class="form_fields"%>
<%=f.label :name,:class=>"control_label"%>
<%=f.text_field(:name)%>
</div>
<div class="form_fields"%>
<%=f.label :grade,:class=>"control_label"%>
<%=f.text_field(:grade)%>
</div>
<div class="form_fields"%>
<%=f.label :branch,:class=>"control_label"%>
<%=f.text_field(:branch)%>
</div>
<div class="form_buttons"%>
<%=submit_tag("submit")%>
</div>
<%end%>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Abit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
   <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
   <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
     <li class="nav-item active">
       <%=link_to"Home", home_index_path%><span class="sr-only">(current)</span></a>
     </li>
     <li class="nav-item active">
       <%=link_to"Aboutus", aboutus_index_path%><span class="sr-only">(current)</span></a>
     </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Droupdown
         </a>

<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
        </li>
        <li class="nav-item active">
       <%=link_to"student",studentinfo_index_path%><span class="sr-only">(current)</span></a>
     </li>
     <li class="nav-item active">
       <%=link_to"faculties", faculties_index_path%><span class="sr-only">(current)</span></a>
     </li>
     <li class="nav-item active">
       <%=link_to"department",department_index_path%><span class="sr-only">(current)</span></a>
       </li>
     <li class="nav-item active">
       <%=link_to"placement", placements_index_path%><span class="sr-only">(current)</span></a>
     </li>
   </from>    
   </div>     
</nav>
<%= yield %>
</body>
</html>

          

app/views/placements/index.html.erb
<h1>Placements#index</h1>
<p>Find me in app/views/placements/index.html.erb</p>

app/views/studentinfo/index.html.erb
<h1>Studentinfo#index</h1>
<p>Find me in app/views/studentinfo/index.html.erb</p>

app/views/studentinfos/_form.html.erb
<%= form_with(model: studentinfo, local: true) do |form| %>
  <% if studentinfo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(studentinfo.errors.count, "error") %> prohibited this studentinfo from being saved:</h2>

      <ul>
      <% studentinfo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/studentinfos/edit.html.erb
<h1>Editing Studentinfo</h1>

<%= render 'form', studentinfo: @studentinfo %>

<%= link_to 'Show', @studentinfo %> |
<%= link_to 'Back', studentinfos_path %>

app/views/studentinfos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Studentinfos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @studentinfos.each do |studentinfo| %>
      <tr>
        <td><%= link_to 'Show', studentinfo %></td>
        <td><%= link_to 'Edit', edit_studentinfo_path(studentinfo) %></td>
        <td><%= link_to 'Destroy', studentinfo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Studentinfo', new_studentinfo_path %>

app/views/studentinfos/new.html.erb
<h1>New Studentinfo</h1>

<%= render 'form', studentinfo: @studentinfo %>

<%= link_to 'Back', studentinfos_path %>

app/views/studentinfos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_studentinfo_path(@studentinfo) %> |
<%= link_to 'Back', studentinfos_path %>